<?php

namespace Database\Seeders;

use App\Models\BookProduct;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


/**
 * Run the database seeds.
 *
 * @return void
 */class BookProductSeeder extends Seeder
{
    public function run()
    {
        $books = [
            [
                'title' => 'A Worn Path',
                'author' => 'Eudora Wetly',
                'grade_level' => 1,
                'cost' => 15,
                'num_pages' => 26,
                'cover_image_path' => null,
            ],
            [
                'title' => 'A Worn Path',
                'author' => 'Eudora Wetly',
                'grade_level' => 2,
                'cost' => 12,
                'num_pages' => 31,
                'cover_image_path' => null,
            ],
            [
                'title' => 'A Box Full of Kisses',
                'author' => 'unknown',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 13,
                'cover_image_path' => null,
            ],
            [
                'title' => 'A Box Full of Kisses',
                'author' => 'unknown',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 9,
                'cover_image_path' => null,
            ],
            [
                'title' => 'A Hole in the Fence',
                'author' => 'Diane Adams',
                'grade_level' => 1,
                'cost' => 2,
                'num_pages' => 3,
                'cover_image_path' => null,
            ],
            [
                'title' => 'A Hole in the Fence',
                'author' => 'Diane Adams',
                'grade_level' => 2,
                'cost' => 2,
                'num_pages' => 2,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Ant and the Grasshopper',
                'author' => 'unknown',
                'grade_level' => 1,
                'cost' => 3,
                'num_pages' => 5,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Ant and the Grasshopper',
                'author' => 'unknown',
                'grade_level' => 2,
                'cost' => 2,
                'num_pages' => 3,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Apple Tree and the Farmer',
                'author' => 'John Galsworthy',
                'grade_level' => 1,
                'cost' => 8,
                'num_pages' => 11,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Apple Tree and the Farmer',
                'author' => 'John Galsworthy',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 7,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Book of 4 Parables (A)',
                'author' => 'unknown',
                'grade_level' => 1,
                'cost' => 8,
                'num_pages' => 32,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Book of 4 Parables (A)',
                'author' => 'unknown',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 21,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Female Reproductive System',
                'author' => 'Glencoe HealthBook',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 12,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Five Chinese Brothers',
                'author' => 'C. Bishop',
                'grade_level' => 1,
                'cost' => 8,
                'num_pages' => 10,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Five Chinese Brothers',
                'author' => 'C. Bishop',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 8,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Galimoto',
                'author' => 'Karen Williams',
                'grade_level' => 1,
                'cost' => 8,
                'num_pages' => 11,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Galimoto',
                'author' => 'Karen Williams',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 9,
                'cover_image_path' => null,
            ],
            [
                'title' => 'I Have a Dream',
                'author' => 'Martin L. King',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 14,
                'cover_image_path' => null,
            ],
            [
                'title' => 'I Have a Dream',
                'author' => 'Martin L. King',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 9,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Jack and the Beanstalk',
                'author' => 'R. Randall',
                'grade_level' => 1,
                'cost' => 6,
                'num_pages' => 8,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Jack and the Beanstalk',
                'author' => 'R. Randall',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 7,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Julius Caesar',
                'author' => 'Shakespeare',
                'grade_level' => 2,
                'cost' => 35,
                'num_pages' => null,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Little Red Riding Hood',
                'author' => 'Charles Perrault',
                'grade_level' => 1,
                'cost' => 6,
                'num_pages' => 7,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Little Red Riding Hood',
                'author' => 'Charles Perrault',
                'grade_level' => 2,
                'cost' => 5,
                'num_pages' => 5,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Lost and Found',
                'author' => 'Anne Schraff',
                'grade_level' => 2,
                'cost' => 20,
                'num_pages' => null,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Male Reproductive System',
                'author' => 'Glencoe HealthBook',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 12,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Mama Panya\'s Pancakes',
                'author' => 'M. Chamberlin',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 21,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Mama Panya\'s Pancakes',
                'author' => 'M. Chamberlin',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 18,
                'cover_image_path' => null,
            ],
            [
                'title' => 'My Rows and Piles of Coins',
                'author' => 'Tololwa Moliel',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 14,
                'cover_image_path' => null,
            ],
            [
                'title' => 'My Rows and Piles of Coins',
                'author' => 'Tololwa Moliel',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 11,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Of Mice and Men',
                'author' => 'John Steinbeck',
                'grade_level' => 2,
                'cost' => 25,
                'num_pages' => null,
                'cover_image_path' => null,
            ],
            [
                'title' => 'P.S. Don\'t Write Back',
                'author' => 'R.L. Stine',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 20,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Rain School',
                'author' => 'J. Rumford',
                'grade_level' => 1,
                'cost' => 5,
                'num_pages' => 5,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Rain School',
                'author' => 'J. Rumford',
                'grade_level' => 2,
                'cost' => 5,
                'num_pages' => 4,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Rikki-Tikki-Tavi',
                'author' => 'Rudyard Kipling',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 12,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Rikki-Tikki-Tavi',
                'author' => 'Rudyard Kipling',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 9,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Sylvestor and the Magic Pebble',
                'author' => 'W. Steig',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 13,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Sylvestor and the Magic Pebble',
                'author' => 'W. Steig',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 10,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Thank You Ma\'am',
                'author' => 'Langston Hughes',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 11,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Thank You Ma\'am',
                'author' => 'Langston Hughes',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 8,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Emperor\'s New Clothes',
                'author' => 'H Anderson',
                'grade_level' => 1,
                'cost' => 10,
                'num_pages' => 13,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Emperor\'s New Clothes',
                'author' => 'H Anderson',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 10,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Giving Tree',
                'author' => 'Shel Silverstein',
                'grade_level' => 1,
                'cost' => 6,
                'num_pages' => 5,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Giving Tree',
                'author' => 'Shel Silverstein',
                'grade_level' => 2,
                'cost' => 5,
                'num_pages' => 5,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Glass Castle',
                'author' => 'Jeannette Walls',
                'grade_level' => 2,
                'cost' => 25,
                'num_pages' => null,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Iron Man and the Blacksmith',
                'author' => 'unknown',
                'grade_level' => 1,
                'cost' => 6,
                'num_pages' => 11,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Iron Man and the Blacksmith',
                'author' => 'unknown',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 8,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Life Cycle',
                'author' => 'Glencoe HealthBook',
                'grade_level' => 2,
                'cost' => 8,
                'num_pages' => 11,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Lorax',
                'author' => 'Dr. Seuss',
                'grade_level' => 1,
                'cost' => 12,
                'num_pages' => 20,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Lorax',
                'author' => 'Dr. Seuss',
                'grade_level' => 2,
                'cost' => 10,
                'num_pages' => 19,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Man Who Loved Flowers',
                'author' => 'Stephen King',
                'grade_level' => 1,
                'cost' => 12,
                'num_pages' => 19,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Man Who Loved Flowers',
                'author' => 'Stephen King',
                'grade_level' => 2,
                'cost' => 10,
                'num_pages' => 15,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Ransom of Red Chief',
                'author' => 'O. Henry',
                'grade_level' => 2,
                'cost' => 12,
                'num_pages' => 27,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Sneetches',
                'author' => 'Dr. Seuss',
                'grade_level' => 1,
                'cost' => 8,
                'num_pages' => 8,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Sneetches',
                'author' => 'Dr. Seuss',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 8,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Three Little Pigs',
                'author' => 'unknown',
                'grade_level' => 1,
                'cost' => 4,
                'num_pages' => 4,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Three Little Pigs',
                'author' => 'unknown',
                'grade_level' => 2,
                'cost' => 2,
                'num_pages' => 3,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The True Story of the Three Little Pigs',
                'author' => 'Jon Scieszke',
                'grade_level' => 1,
                'cost' => 6,
                'num_pages' => 8,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The True Story of the Three Little Pigs',
                'author' => 'Jon Scieszke',
                'grade_level' => 2,
                'cost' => 5,
                'num_pages' => 6,
                'cover_image_path' => null,
            ],
            [
                'title' => 'The Werewolf\'s First Night',
                'author' => 'R.L. Stine',
                'grade_level' => 2,
                'cost' => 10,
                'num_pages' => 19,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Winter Dreams',
                'author' => 'F. Scott Fitagerald',
                'grade_level' => 2,
                'cost' => 22,
                'num_pages' => 57,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Yertle the Turtle',
                'author' => 'Dr. Seuss',
                'grade_level' => 1,
                'cost' => 8,
                'num_pages' => 10,
                'cover_image_path' => null,
            ],
            [
                'title' => 'Yertle the Turtle',
                'author' => 'Dr. Seuss',
                'grade_level' => 2,
                'cost' => 6,
                'num_pages' => 9,
                'cover_image_path' => null,
            ],
        ];

        DB::table('book_products')->insert($books);
    }

}
